# Generated by Django 4.2.3 on 2023-07-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
