# Generated by Django 4.2.5 on 2023-10-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapi', '0002_alter_invoicedetail_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_name',
            new_name='CustomerName',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_no',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
